### ISSUE TITLE
Docs reference 0.1.2 but it's not yet published on Clojars

### ISSUE THREAD

**Issue by belucid** [helpshift/hydrox#5]
It's unusual to make the version in the default branch README, which is where all new users will land:

https://github.com/helpshift/hydrox

Not match the latest version published on Clojars:

https://clojars.org/helpshift/hydrox

Or else every person's first experience with Hydrox is:

``` console
Could not find artifact helpshift:hydrox:jar:0.1.2 in central (https://repo1.maven.org/maven2/)
Could not find artifact helpshift:hydrox:jar:0.1.2 in clojars (https://clojars.org/repo/)
This could be due to a typo in :dependencies or network issues.
If you are behind a proxy, try setting the 'http_proxy' environment variable.
```

**Comment by hoebat** [comment]
Hey!

Thanks for pointing this out. I had a network issue before and forgot that it didn’t upload. 

Please try again!

Chris.

**Comment by hoebat** [comment]
It's now on clojars =)

**Comment by belucid** [comment]
Super!
